<a href="https://colab.research.google.com/github/GabeMaldonado/AIforMedicine/blob/master/AIforMed_Week3_Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exctracting Sub Volumes 

As we learn before, it is not possible to pass the entire MRI image into the model. We need to extract sub volumes of the data to then feed the model. 
In this Lab we will extract a small "cube" from the image. We will perform the extraction using a 1D np array as an image.

In [0]:
import numpy as np

In [2]:
# Create np.array representing the image
image = np.array([10, 11, 12, 13, 14, 15])
image

array([10, 11, 12, 13, 14, 15])

In [3]:
# Compute dimensions of the image
image_length = image.shape[0]
image_length

6

## Sub Volumes
We need to define a "patch_length" which will be the size of the sub volume to be extracted.

In [0]:
# Define patch length
patch_length = 3

To extract a patch/sub volume that is the size if ```patch_length``` we need to define an index at which to start the patch. 

In [0]:
# Define start index
start_i = 0

In [7]:
# Increase index by 1

print(f"Start index: {start_i}")
end_i = start_i + patch_length
print(f"End index: {end_i}")

# Extract sub volume from the image
sub_section = image[start_i:end_i]
print(sub_section)

# Increase index by 1
start_i += 1

Start index: 0
End index: 3
[10 11 12]


If run the above cell multiple times, we will see that the sub volume being returned is will no longer be of ```patch_length``` size. This will create a problem as the neural network/model would only accept sub volumes of a particular size and dimension. 
*Start indices* are normally selected randomly so we need to ensure that the random number generator is set up to avoid the edges of the image object. 


In [8]:
# Start index to 3 and select a valid patch

start_i = 3 
print(f"Start index: {start_i}")

end_i = start_i + patch_length
print(f"End index: {end_i}")

sub_section = image[start_i:end_i]
print(sub_section)

Start index: 3
End index: 6
[13 14 15]


In [10]:
# Compute and print the largest valid value for a start index
print(f"The largests start index for which "
      f"a subsection is still valid is "
      f"{image_length - patch_length}")

The largests start index for which a subsection is still valid is 3


In [11]:
# Compute and print the range of valid start indices

print(f"The range of valid start indices:")

# Compute valid start indices, include upper bound
valid_start_i = [i for i in range(image_length - patch_length + 1)]
print(valid_start_i)

The range of valid start indices:
[0, 1, 2, 3]


## Random Selection of Start Indices

Selecting a random integer for the start index for our 1D image.




In [13]:
# Choose a random int for the start index
start_i = np.random.randint(image_length - patch_length + 1)
print(f"Randomly selected start index: {start_i}")


Randomly selected start index: 3


In [14]:
# Randomly select multiple start indices in a loop

for _ in range(10):
  start_i = np.random.randint(image_length - patch_length +1)
  print(f"Randomly selected start index: {start_i}")

Randomly selected start index: 1
Randomly selected start index: 1
Randomly selected start index: 2
Randomly selected start index: 1
Randomly selected start index: 2
Randomly selected start index: 0
Randomly selected start index: 1
Randomly selected start index: 1
Randomly selected start index: 3
Randomly selected start index: 2
