<a href="https://colab.research.google.com/github/GabeMaldonado/AIforMedicine/blob/master/AIforMed_C2_W1_Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Calculating Risk Scores Using Python
In this lab we'll calculate the risk scores for:
*   Atrial Fibrilation -- CHADs-VASC score
*   Liver Disease - MELD score
*   Heart Disease - ASCVD score



In [0]:
# Compute CHADs-Vasc score


def chads_vasc_score(input_c, input_h, input_a2, input_d, input_s2, input_v, input_a, input_sc):
    # congestive heart failure
    coef_c = 1 
    
    # Coefficient for hypertension
    coef_h = 1 
    
    # Coefficient for Age >= 75 years
    coef_a2 = 2
    
    # Coefficient for diabetes mellitus
    coef_d = 1
    
    # Coefficient for stroke
    coef_s2 = 2
    
    # Coefficient for vascular disease
    coef_v = 1
    
    # Coefficient for age 65 to 74 years
    coef_a = 1
    
    # TODO Coefficient for female
    coef_sc = 1
    
    # Calculate the risk score
    risk_score = (input_c * coef_c) +\
                 (input_h * coef_h) +\
                 (input_a2 * coef_a2) +\
                 (input_d * coef_d) +\
                 (input_s2 * coef_s2) +\
                 (input_v * coef_v) +\
                 (input_a * coef_a) +\
                 (input_sc * coef_sc)
    
    return risk_score

Calculate risk score for a patient with the following inputs:
<pre>
*   Congestive heart failure : NO
*   Hypertention             : YES
*   Age 75 or older          : NO
*   Diabetis Mellitus        : NO
*   Stroke                   : NO
*   Vascular disease         : YES
*   Age 65 to 74             : NO
*   Female?                  : YES 
</pre>

In [3]:
# Calculate CHADs-Vasc score for patient above

tmp_c = 0
tmp_h = 1
tmp_a2 = 0
tmp_d = 0
tmp_s2 = 0
tmp_v = 1
tmp_a = 0
tmp_sc = 1

print(f"The CHADs-Vasc score for this patient is: ",
      f"{chads_vasc_score(tmp_c, tmp_h, tmp_a2, tmp_d, tmp_s2, tmp_v, tmp_a, tmp_sc)}")

The CHADs-Vasc score for this patient is:  3


## Calcualate Score for Liver Disease (MELD)



In [0]:
# Implement function to calculate MELD score

import numpy as np

def liver_disease_mortality(input_creatine, input_bilirubin, input_inr):
  """
    Calculate the probability of mortality given that the patient has
    liver disease. 
    Parameters:
        Creatine: mg/dL
        Bilirubin: mg/dL
        INR: 
   """
 
  # Coefficient Values
  coef_creatine = 0.957
  coef_bilirubin = 0.378
  coef_inr = 1.12
  intercept = 0.643

  # Calculate the natural logarithm of inpuit variables
  log_cre = np.log(input_creatine)
  log_bil = np.log(input_bilirubin)
  log_inr = np.log(input_inr)

  # Compute output
  meld_score = (coef_creatine * log_cre) +\
               (coef_bilirubin * log_bil) +\
               (coef_inr * log_inr) +\
               intercept

  # Multiply meld_score by 10 to get final score
  meld_score = meld_score * 10

  return meld_score


Calculate MELD score for the following patient:

<pre>
*   Creatinine       : 1 mg/dl
*   Bilirubin        : 2 mg/dL
*   INR              : 1.1
</pre>

In [13]:
# Compute MELD score
tmp_meld_score= liver_disease_mortality(1.0, 2.0, 1.1 )
print(f"The patient's MELD score is: {tmp_meld_score:.2f}")

The patient's MELD score is: 10.12


## Calculating ASCVD Risk Score for Heart Disease

Coefficients for this function:

<pre>
*  Ln(Age):                                     17.114
*   Ln(total cholesterol):                      0.94
*   Ln(HDL):                                   -18.920
*   Ln(Age) x Ln(HDL-C):                        4.475
*   Ln (Untreated systolic BP):                 27.820
*   Ln (Age) x Ln 10 (Untreated systolic BP):   -6.087
*   Current smoker (1 or 0):                    0.691
*   Diabetes (1 or 0):                          0 874

</pre>

Remember that after you calculate the sum of the products (of inputs and coefficients), use this formula to get the risk score:

$$Risk = 1 - 0.9533^{e^{sumProd - 86.61}}$$

This is 0.9533 raised to the power of this expression: $e^{sumProd - 86.61}$, and not 0.9533 multiplied by that exponential.

In [0]:
def ascvd(x_age,
          x_cho,
          x_hdl,
          x_sbp,
          x_smo,
          x_dia,
          verbose=False):
  """
  Atherosclerotic Cardiovascular Diseas
  (ASCVD) Risk Estimator Plus
  """

  # Define Coefficients
  b_age = 17.114
  b_cho = 0.94
  b_hdl = -18.92
  b_age_hdl = 4.475
  b_sbp = 27.82
  b_age_sbp = -6.087
  b_smo = 0.691
  b_dia = 0.874

  # Calculate the sum of products of inputs and coefficients
  sum_prod = b_age * np.log(x_age) +\
             b_cho * np.log(x_cho) +\
             b_hdl * np.log(x_hdl) +\
             b_age_hdl * np.log(x_age) * np.log(x_hdl) +\
                b_sbp * np.log(x_sbp) +\
                b_age_sbp * np.log(x_age) * np.log(x_sbp) +\
                b_smo * x_smo + \
                b_dia * x_dia
    
  if verbose:
      print(f"np.log(x_age):{np.log(x_age):.2f}")
      print(f"np.log(x_cho):{np.log(x_cho):.2f}")
      print(f"np.log(x_hdl):{np.log(x_hdl):.2f}")
      print(f"np.log(x_age) * np.log(x_hdl):{np.log(x_age) * np.log(x_hdl):.2f}")
      print(f"np.log(x_sbp): {np.log(x_sbp):2f}")
      print(f"np.log(x_age) * np.log(x_sbp): {np.log(x_age) * np.log(x_sbp):.2f}")
      print(f"sum_prod {sum_prod:.2f}")
      
  # TODO: Risk Score = 1 - (0.9533^( e^(sum - 86.61) ) )
  risk_score = 1 - 0.9533**(np.exp(sum_prod-86.61))
  
  return risk_score


  


In [16]:
tmp_risk_score = ascvd(x_age=55,
                      x_cho=213,
                      x_hdl=50,
                      x_sbp=120,
                      x_smo=0,
                      x_dia=0, 
                      verbose=True
                      )
print(f"\npatient's ascvd risk score is {tmp_risk_score:.2f}")

np.log(x_age):4.01
np.log(x_cho):5.36
np.log(x_hdl):3.91
np.log(x_age) * np.log(x_hdl):15.68
np.log(x_sbp): 4.787492
np.log(x_age) * np.log(x_sbp): 19.19
sum_prod 86.17

patient's ascvd risk score is 0.03


## Numpy and Pandas Operations

Here we will compare how pandas and numpy functions are slightly different. 

In [0]:
import pandas as pd
import numpy as np
import sklearn

In [0]:
# Functions to generate data
import sklearn


def generate_data(n=200):
    df = pd.DataFrame(
        columns=['Age', 'Systolic_BP', 'Diastolic_BP', 'Cholesterol']
    )
    df.loc[:, 'Age'] = np.exp(np.log(60) + (1 / 7) * np.random.normal(size=n))
    df.loc[:, ['Systolic_BP', 'Diastolic_BP', 'Cholesterol']] = np.exp(
        np.random.multivariate_normal(
            mean=[np.log(100), np.log(90), np.log(100)],
            cov=(1 / 45) * np.array([
                [0.5, 0.2, 0.2],
                [0.2, 0.5, 0.2],
                [0.2, 0.2, 0.5]]),
            size=n))
    return df



In [0]:
def f(x):
    p = 0.4 * (np.log(x[0]) - np.log(60)) + 0.33 * (
            np.log(x[1]) - np.log(100)) + 0.3 * (
                np.log(x[3]) - np.log(100)) - 2.0 * (
                np.log(x[0]) - np.log(60)) * (
                np.log(x[3]) - np.log(100)) + 0.05 * np.random.logistic()
    if p > 0.0:
        return 1.0
    else:
        return 0.0

In [0]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [0]:
def load_data(n=200):
    np.random.seed(0)
    df = generate_data(n)
    for i in range(len(df)):
        df.loc[i, 'y'] = f(df.loc[i, :])
        X = df.drop('y', axis=1)
        y = df.y
    return X, y

In [0]:
# Generate data, features (X) and labels (y)

X, y = load_data(100)

In [25]:
# Explore features
X.head()

Age  Systolic_BP  Diastolic_BP  Cholesterol
0  77.196340    78.379387     86.862625    83.344731
1  63.529850    85.439716     77.288707   107.483614
2  69.003986    98.406978     85.411057   118.495893
3  82.638210   100.362697     71.119650    87.737132
4  78.346286   121.854369     92.013270    99.121558

In [26]:
# Explore labels
y.head()

0    0.0
1    0.0
2    1.0
3    1.0
4    1.0
Name: y, dtype: float64

## How does *mean* differ from pandas and numpy?

Even though numpy and pandas are widely used to calculate the mean without major implications, we'll see that they slightly differ. 

### Pandas.Dataframe.mean

Apply the **mean** to the pandas DF.


In [29]:
# Apply the mean to the DF without choosing an axis

print(f"Pandas: X_mean()=\n {X.mean()}\n")

# Apply the mean function to axis=0

print(f"Pandas: X.mean()=\n {X.mean(axis=0)}\n")

Pandas: X_mean()=
 Age              61.145103
Systolic_BP      99.762232
Diastolic_BP     91.147442
Cholesterol     100.925003
dtype: float64

Pandas: X.mean()=
 Age              61.145103
Systolic_BP      99.762232
Diastolic_BP     91.147442
Cholesterol     100.925003
dtype: float64



For pandas DFs, by default:
*   Pandas treats every column separetely
*   We can also explicitly instruct the function to calculate the mean for each column by setting axis=0
*   Same result, for both cases

### Np.array.mean()

Compare to what happens when we call ```np.mean()``` and the data is stored in a numpy array:

In [52]:
# Store data into a np.array
X_np = np.array(X)

# View first two rows of the array
print(f"First two rows of the array: \n {X_np[0:2,:]}")

First two rows of the array: 
 [[ 77.19633951  78.37938696  86.86262497  83.344731  ]
 [ 63.52985022  85.43971583  77.28870706 107.48361434]]


In [57]:
# Apply np.mean function without specifying an axis

print(f"Np.mean: X_np = \n {X_np.mean()}\n")

# Apply np.mean on axis=0
print(f"Np.mean: X_np = \n {X_np.mean(axis=0)}")


Np.mean: X_np = 
 88.24494498174543

Np.mean: X_np = 
 [ 61.14510296  99.76223179  91.14744211 100.92500307]


As we can see, np.mean is different from pandas mean
*   By default, the mean is calculated for all values in the rows and columns. We get a single mean fro the entire 2D array. 
*   To explicitly calculate the mean for each column separetely, we must pass ```axis=0```

In [60]:
X.mean(axis=1)

0     81.445771
1     83.435472
2     92.829479
3     85.464422
4     97.833871
        ...    
95    99.541948
96    78.501428
97    93.142468
98    89.697351
99    82.368333
Length: 100, dtype: float64

In [61]:
X_np.mean(axis=1)

array([ 81.44577061,  83.43547186,  92.82947865,  85.464422  ,
        97.83387051,  81.072484  ,  86.33561313,  94.38186756,
        91.44869879,  78.38641822,  92.52497797,  90.8918213 ,
        85.94232312,  94.68155003,  88.35523072,  83.09195724,
        99.25824219,  77.52898522,  89.02290228,  92.41751773,
        86.62106654,  88.65527054,  96.03359073,  84.3332454 ,
        88.26611326,  80.68750509,  90.3045462 ,  95.77564576,
        87.57002631,  91.09832685,  95.93260142,  95.63631552,
        82.02753088,  76.26296263,  80.74083167,  97.99643525,
        88.92994246,  88.52346543,  92.47975217,  85.24978965,
        91.22361032,  82.02097648,  83.30132681,  93.73320268,
        89.72061507,  82.43749193,  82.59658942,  91.60508423,
        86.646893  ,  80.88167   ,  82.68046158,  90.5062123 ,
        90.87729272,  81.60945765,  91.07059764,  87.41581228,
        89.58799871, 107.2683618 ,  90.24279104,  88.28334728,
        86.89579322,  78.3310002 ,  92.70042337,  76.84